export const GET_ASSIGNMENTS = 'GET_ASSIGNMENTS';
export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
export const UPDATE_ASSIGNMENT = 'UPDATE_ASSIGNMENT';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
export const TOGGLE_ASSIGNMENT_DIALOG = 'TOGGLE_ASSIGNMENT_DIALOG';
export const SELECT_ASSIGNMENT = 'SELECT_ASSIGNMENT';
export const SELECT_ALL_ASSIGNMENTS = 'SELECT_ALL_ASSIGNMENTS';
export const UPLOAD_ASSIGNMENT = 'UPLOAD_ASSIGNMENT';
